export { crearCartaHTML } from "./crear-carta"
export { crearDeck } from "./crear-deck"
export { estadoBotones } from "./estado-botones"
export { pedirCarta } from "./pedir-carta"
export { turnoComputadora } from "./turno-computadora"
export { valorCarta } from "./valor-carta"
